# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-16 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklistapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
