# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('tasklistapp', '0002_tasklist_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['priority']},
        ),
        migrations.AlterModelOptions(
            name='tasklist',
            options={'ordering': ['name'], 'verbose_name_plural': 'Task Lists'},
        ),
        migrations.AlterUniqueTogether(
            name='tasklist',
            unique_together=set([('group', 'slug')]),
        ),
    ]
